version: 2
updates:
  - package-ecosystem: gomod
    directory: /snyk-controller-helm
    schedule:
      interval: daily
    allow:
      - dependency-name: "github.com/aws-quickstart/quickstart-helm-resource-provider"